# Generated by Django 6.0.4 on 2026-04-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(verbose_name='ID пользователя')),
                ('username', models.CharField(blank=True, max_length=100, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('command', models.CharField(choices=[('/start', 'Старт'), ('/help', 'Помощь'), ('/calc', 'Калькулятор'), ('/quote', 'Цитата'), ('/weather', 'Погода'), ('/history', 'История'), ('/clear', 'Очистка'), ('unknown', 'Неизвестная')], default='unknown', max_length=20, verbose_name='Команда')),
                ('text', models.TextField(verbose_name='Полный текст сообщения')),
                ('result', models.TextField(blank=True, verbose_name='Результат бота')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время запроса')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
