# Generated by Django 6.0.4 on 2026-04-25 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='command',
            field=models.CharField(choices=[('/start', 'Старт'), ('/help', 'Помощь'), ('/calc', 'Калькулятор'), ('/quote', 'Цитата'), ('/history', 'История'), ('/clear', 'Очистка'), ('unknown', 'Неизвестная')], default='unknown', max_length=20, verbose_name='Команда'),
        ),
    ]
